### ISSUE TITLE
Feature Request: Freely choose frequencies and test sound color too.

### ISSUE THREAD

**Issue by AlexOnFOSS** [woheller69/audiometry#11]
It would be great for the user to be able to easily swipe thru the frequencies with fingers. For example to have something like two bars and a toggle on/off button. 
1) The bars are there to swipe between the frequencies from low to high. Each ear with its own bar. 
2) The toggle button is there to be able to swipe thru the frequencies with both bars (ears) simultaneous or separately.  
That way someone would be able to easily find out 1) if frequencies sound different and if yes, 2) how much the hearing is displaced (like 100HZ in one are vs 125Hz in the other ear).

In practice  someone would have to swipe both bars simultaneous until he realizes that the ears hear the one sound different. Than he can press the toggle button to move the bars separately until the sound color on both ears matches again. The difference between the bars is how much the hearing is displaced. 

I hope I have explained me well. If not just tell me and I will give it another try.

Best wishes, 
Alex.

**Comment by woheller69** [comment]
That sounds like a different app.

what about using Signal Generator from F-Droid?

https://github.com/billthefarmer/sig-gen

**Comment by AlexOnFOSS** [comment]
Thx for the advice, i will give it a try.
