### ISSUE TITLE
Brief interpretation of the result can be nice

### ISSUE THREAD

**Issue by lamyergeier** [woheller69/audiometry#13]
![image](https://github.com/woheller69/audiometry/assets/42092626/6aed6452-0841-4a7e-af1a-e55821c4eec0)

I got the above results. Could you please clarify the following doubts:
1. Can the test be done upto 20kHz as normal hearing can be upto that frequency?
2. My mobile phone doesn't have a headphone jack, so I use [USB-C to 3.5 mm Headphone Jack Adapter - Apple](https://www.apple.com/shop/product/MU7E2AM/A/usb-c-to-35-mm-headphone-jack-adapter). Do you think that this can affect the test results?
3. Why results are in hegative dB? What does 0 dB signify?

**Comment by woheller69** [comment]
To me it seems you have not gone through calibration...

**Comment by woheller69** [comment]
https://www.asha.org/public/hearing/Degree-of-Hearing-Loss/
