### ISSUE TITLE
Feature Request :: Hearing Aid Feature

### ISSUE THREAD

**Issue by Vamp898** [woheller69/audiometry#14]
Hi there,

a lot of these apps on the Google App Store have the feature, to use the measurement to turn your earphones into hearing aids.

I use this feature for the self-build hearing aid i made for my father. But sadly these closed source apps have a lot of downsides and anti-features.

It would be awesome if this app could be extended to pickup the microphone sound and play it back via the earphones with the option, of course, to apply the measured EQ to the microphone sound.

That way, this app could be used to turn earphones into hearing aid too.

**Comment by woheller69** [comment]
That is a completely different app.
You need an equalizer app, where you set the data measured here.

I will not implement that in this app
