### ISSUE TITLE
App gets stuck during full calibration

### ISSUE THREAD

**Issue by ringprince** [woheller69/audiometry#5]
While I was able to finish one full calibration, the app got stuck twice during the attempt to add a second full calibration. As a full calibration is a lengthy process, I have not attempted a third re-try.

**Comment by woheller69** [comment]
Can you describe what exactly happened? What does "got stuck" mean? Did it stop playing tones? Not react to touch anymore?
Other? I have never had such a problem.

Full calibration is the same as a normal full test for the app. After completion of the test the app checks whether this activity was started as a calibration or test and then stores the data accordingly.

**Comment by ringprince** [comment]
It would not continue to play tones. It would still react to the 'back' button.

But by now I have experienced problems with other apps, too. So likely a phone issue and can be closed here. I will re-open if necessary.
