### ISSUE TITLE
Add some help for result interpretation

### ISSUE THREAD

**Issue by bluezed** [woheller69/audiometry#8]
Just found the App on FDroid and did a test. It went smoothly and I got my results. But knowing nothing about audiometry I don't know how to interpret them? Some kind of guide or at least a link to some resources would be very helpful.

Ideally the app would provide some kind of scoring or a rough comparison to what's considered "normal" at different ages.

**Comment by woheller69** [comment]
Some information about age related hearing loss can be found 
here:

       https://en.m.wikipedia.org/wiki/Presbycusis#Diagnosis

more information for interpretation can be found here:

      https://en.m.wikipedia.org/wiki/Audiogram

**Comment by kowalcj0** [comment]
If I understood the `Diagnosis` section of the Presbycusis article correctly then my results are decent as most results are above 25dB threshold. 
Got this kind od results after quick headphones calibration.

```
Thresholds right
125 Hz -50.0 dBHL
250 Hz -39.3 dBHL
500 Hz -32.3 dBHL
1000 Hz -30.3 dBHL
2000 Hz -26.6 dBHL
3000 Hz -22.2 dBHL
4000 Hz -22.5 dBHL
6000 Hz -32.4 dBHL
8000 Hz -40.5 dBHL

Thresholds left
125 Hz -50.0 dBHL
250 Hz -39.3 dBHL
500 Hz -32.3 dBHL
1000 Hz -30.3 dBHL
2000 Hz -26.6 dBHL
3000 Hz -22.2 dBHL
4000 Hz -22.5 dBHL
6000 Hz -32.4 dBHL
8000 Hz -40.5 dBHL
```

![Screenshot_20220221-220024_hEARtest](https://user-images.githubusercontent.com/910451/155031145-b6003c3c-ccc7-442a-a050-9b0d4b4f3604.png)

**Comment by woheller69** [comment]
that looks very strange. If you did the quick calibration at 1000Hz yourself then at 1000Hz you should be at 0

**Comment by woheller69** [comment]
It looks like you just let the simple calibration run without listening and responding to the tones...

**Comment by kowalcj0** [comment]
I did respond to them.
I'll run the simple calibration again today and rerun the test.

**Comment by woheller69** [comment]
delete calibration before you calibrate again

**Comment by kowalcj0** [comment]
So, I've deleted the calibration, then plugged in my IEMs Shure se846 to OnePlus 6 and ran the simple test.
Afterwards, I ran a full test in a quiet room, (although there was a brief moment of noise outside) and this time I got following results:

```
Thresholds right
125 Hz -22.0 dBHL
250 Hz -9.0 dBHL
500 Hz -2.0 dBHL
1000 Hz -2.3 dBHL
2000 Hz 3.7 dBHL
3000 Hz 8.1 dBHL
4000 Hz 7.8 dBHL
6000 Hz -2.1 dBHL
8000 Hz -10.2 dBHL

Thresholds left
125 Hz -19.7 dBHL
250 Hz -10.7 dBHL
500 Hz -2.0 dBHL
1000 Hz 0.0 dBHL
2000 Hz 3.7 dBHL
3000 Hz 8.1 dBHL
4000 Hz 7.8 dBHL
6000 Hz -2.1 dBHL
8000 Hz -10.2 dBHL
```

![Screenshot_20220223-203406_hEARtest](https://user-images.githubusercontent.com/910451/155404243-5275c0fd-24cf-4ad7-ad5d-9ba74cd13cb5.png)

**Comment by woheller69** [comment]
that is how it should look like.

**Comment by kowalcj0** [comment]
Great. Thank you!
 
PS. I forgot to mention that prior to redoing the calibration and the test I've updated the app to v1.3

**Comment by woheller69** [comment]
are your earphones passive or do they have built in electronics like volume control or loudness?

**Comment by kowalcj0** [comment]
These are passive IEMs. I'm not sure whether that dip is caused by my hearing getting worse, or some sort deficiency of my headphones in that frequency range (here's a page with some inf on its freq resp 
before and after EQing https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_in-ear_2019v2/Shure%20SE846) or maybe the phone's built-in DAC doesn't do well I that range.
It's also possible that all of the above are true :)

BTW. I also tried using a decent USB dongle DAC, but for some reason it introduces some delay and brief distortion when a new sample is being played. So, I gave up on using it for testing.

**Comment by woheller69** [comment]
does your phone have a built in equalizer?
My devices don't, but I just read some devices have an equalizer in settings -> sound quality
I do not know if this would influence the result

**Comment by kowalcj0** [comment]
Yes it does (it's called AudioFX) but it's always off.
If it was on, the it'd certainty affect the results.

BTW. Is there a list of devices or combination of mobiles & headphones which were proven to provode reliable results?

**Comment by woheller69** [comment]
no, there is no such list
