### ISSUE TITLE
Error: cannot get lower

### ISSUE THREAD

**Issue by ghost** [woheller69/audiometry#9]
Can't finish the calibration (both simple and full).

**Comment by woheller69** [comment]
this means your earphones are too loud, or your ears are too good :-)
With my earphones I am way off that limit...
I need to set a fixed amplifier volume in the app. The various levels are calculated digitally.
Maybe I can make volume a preference.

**Comment by woheller69** [comment]
Can you try this? Just remove .zip and install.
Gain is reduced from 9 to 4. No idea if that is sufficient...
[hEARtest_gain4.apk.zip](https://github.com/woheller69/audiometry/files/8104258/hEARtest_gain4.apk.zip)

This version also has a dual user capability.

**Comment by ghost** [comment]
This version works fine. Though at the first attempt to calibrate I have catched this error once again, the second time it has calibrated  normally.

**Comment by woheller69** [comment]
Ok, great. I will wait and see how often this happens and which gain values would be required.
The calibration and test data must not be mixed between versions with different gains.
In case I make this a preference every change of this setting will require to wipe calibration and test results.
Which should not be a big issue because the problem will usually arise during first calibration.

**Comment by woheller69** [comment]
Are your earphones passive or do they have volume control or other built in electronics?

**Comment by ghost** [comment]
I have simple headphones:
JBL T110

**Comment by Yak-Herder** [comment]
I encountered this problem as well but only at 1000Hz, Right ear. With a full calibration, it happened at the same place. No problem with the lower frequencies. With debug on, I get alternating toasts which say "Amplitude: 1" and "Error: can't get lower". I don't hear a sound, and I don't tap the screen, it just gets stuck in that loop.

I'm using Bluetooth earphones. They do have buttons for volume, but they control the phone's volume.

I just tried your gain 4 version above, and it worked for me, as well.

**Comment by tmakarios** [comment]
Same problem here at 500 Hz using second-hand [Audio-Technica ATH-M50x headphones](https://www.rtings.com/headphones/reviews/audio-technica/ath-m50x).  The gain 4 APK worked for me.

**Comment by woheller69** [comment]
Here comes an updated version where gain can be switched (via 3 dots options menu).
Gain is saved in backup files so when restored the gain belonging to the backup will be restored.
Please try. This version has the low gain as default.

If you have a backup of your data you should be able to use the normal F-Droid version in future (once published).

[hEARtest_switch_gain.apk.zip](https://github.com/woheller69/audiometry/files/8763348/hEARtest_switch_gain.apk.zip)
